language: python
python:
        - "3.5"
        - "3.6"
        - "3.7"

install:
        - pip install flake8 pylint

jobs:
        - include:
                - stage: code style
                  script: pylint src

stages:
        - name: code style
