dist: xenial
language: python
python:
  - "3.8"
  - "3.7"
install:
  - pip install black flake8

script: pytest

jobs:
  - include:
    - stage: lint
      script: flake8
      script: black --check --quiet .

stages:
  - lint
  - test

branches:
  only:
    - master
    - 2.2-dev
