dist: xenial
language: python
python:
        - "3.6"
        - "3.7"

install:
        - pip install flake8 pylint

script: pytest tests

jobs:
        - include:
                - stage: code style
                  script: pylint3 --extension-pkg-whitelist=lxml src

stages:
        - test
        - code style

branches:
        only:
                - master
                - dev
