language: python
python:
        - "3.5"
        - "3.6"
        - "3.7"

install:
        - pip install notify2 flake8 pylint

jobs:
        - include:
                - stage: code style
                  script: pylint
