name: Python package

on:
  push:
    branches:
      - master
      - '[0-9].[0-9]-dev'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]-dev'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set Python ${{ matrix.python-version }} environment up
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
      - name: Check Python code formatting with black
        run: |
          black --check --quiet .
      - name: Lint with flake8
        run: flake8
      - name: Test with pytest
        run: |
          pytest
